# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_hired',
            field=models.DateTimeField(null=True),
        ),
    ]
